version: "3.9"

services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.50
    user: root
    ports:
      - 80:16686 # Jaeger UI
      - 4317:4317 # OpenTelemetry Protocol (OTLP) over gRPC
      - 4318:4318 # OpenTelemetry Protocol (OTLP) over HTTP
      - 14268:14268 # jaeger.thrift directly from clients
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key
    volumes:
      - jaeger_data:/badger
    depends_on:
      - prometheus
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090"
      
volumes:
  jaeger_data:

