version: "3.9"

services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.50
    ports:
      - 80:16686 # Jaeger UI
      - 4317:4317 # OpenTelemetry Protocol (OTLP) over gRPC
      - 4318:4318 # OpenTelemetry Protocol (OTLP) over HTTP
      - 14268:14268 # jaeger.thrift directly from clients
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - ES_TAGS_AS_FIELDS_ALL=true
    depends_on:
      - elasticsearch
    restart: on-failure
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    environment:
      - "discovery.type=single-node"
      - "cluster.name=jaeger"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200"
      - "9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: on-failure
  
volumes:
  esdata:

